//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoCalCodeCamp.LoggingDemo.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoCalCodeCamp.LoggingDemo.i18n.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Name or Tag.
        /// </summary>
        public static string AppNameOrTag {
            get {
                return ResourceManager.GetString("AppNameOrTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nah, I&apos;m Done....
        /// </summary>
        public static string GetMeOuttaHere {
            get {
                return ResourceManager.GetString("GetMeOuttaHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host or IP Address.
        /// </summary>
        public static string HostOrIp {
            get {
                return ResourceManager.GetString("HostOrIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Settings.
        /// </summary>
        public static string LoggingSettingsTitle {
            get {
                return ResourceManager.GetString("LoggingSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Test Log.
        /// </summary>
        public static string LoggingTestTitle {
            get {
                return ResourceManager.GetString("LoggingTestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Fake Exception.
        /// </summary>
        public static string ReportFakeException {
            get {
                return ResourceManager.GetString("ReportFakeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Another Test Log?.
        /// </summary>
        public static string SendAnotherTest {
            get {
                return ResourceManager.GetString("SendAnotherTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try it out!.
        /// </summary>
        public static string TryItOut {
            get {
                return ResourceManager.GetString("TryItOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yep!.
        /// </summary>
        public static string Yep {
            get {
                return ResourceManager.GetString("Yep", resourceCulture);
            }
        }
    }
}
